### ISSUE TITLE
PHP 7 RC2+ 

### ISSUE THREAD

**Issue by Jackysi** [php-memcached-dev/php-memcached#199]
Since PHP7 RC2 and above the Memcached issues bellow error when using Session save handler. I am not sure if this is PHP error or Memcached Extension but either way I still have this issue usig RC7 and latest repo sources.

```
PHP Catchable fatal error:  session_regenerate_id(): Failed to create session ID: memcached (path: 127.0.0.1:11211) in /var/www/vhosts/advancedtomato.com/httpdocs/file.php on line 143
```

**Comment by srogier** [comment]
I have the same issue on RC7.

I also had the same kind of issue on a custom session handler. I resolved it by changing the return of the read method in the handler. Before, it returned false when there where no data, no it returns an empty string (http://nl1.php.net/manual/en/sessionhandler.read.php).

Maybe it's the same issue in the extension.

**Comment by blu3gui7ar** [comment]
Same issue on PHP7 release.

 E_RECOVERABLE_ERROR: session_regenerate_id(): Failed to create(read) session ID: memcached (path: 127.0.0.1:11211) {"code":4096,"message":"session_regenerate_id(): Failed to create(read) session ID: memcached (path: 127.0.0.1:11211

**Comment by gangbo** [comment]
+1

**Comment by dvershinin** [comment]
+1 Have the same error running php-pecl-memcached with PHP 7.0.2 from remi repository on CentOS 7

**Comment by mkoppanen** [comment]
Can you check with current php7 branch? I merged a PR that should solve this issue.

**Comment by srogier** [comment]
@mkoppanen Thank you, but I still have the same issue after checking with the new php7 branch.

**Comment by mkoppanen** [comment]
@srogier,

can you elaborate?

**Comment by srogier** [comment]
it's still the same error "session_regenerate_id(): Failed to create new session ID: memcached (path: mymemcachesession:11211) "

I now use PHP 7.0.2.

This is the script I use to test the error : https://gist.github.com/srogier/fc18b4747464e4e5fcb0

**Comment by mkoppanen** [comment]
@srogier,

thanks for the reproduce script. I'll try to see if i can get this to happen locally. Will report back shortly

**Comment by mkoppanen** [comment]
#214 fixes this among other issues. The underlying cause was a php bug: https://github.com/php/php-src/pull/1739

**Comment by HansVanEijsden** [comment]
@mkoppanen thanks for fixing it. Happy again. 😃

**Comment by srogier** [comment]
Everything seems ok :+1: 
Thanks !

**Comment by Jackysi** [comment]
Extrodinary news! Will test and report back soon!

**Comment by Jackysi** [comment]
Ogh made fool out of my self. Thought this is another project. There are still some issues but ot generally works yeah.

**Comment by mscreenie** [comment]
I get this bug in 7.0.8-0ubuntu0.16.04.2 . Guessing this is fixed in latest.

**Comment by sodabrew** [comment]
@mscreenie What version of memcached module are you using? 214 is currently merged to the php7 branch, but isn't in a release module yet.

**Comment by mscreenie** [comment]
Hey @sodabrew , my php-memcached is 

```
memcached support	enabled
Version	2.2.0
libmemcached version	1.0.18

```

**Comment by shubaly** [comment]
@sodabrew I'm getting the "E_RECOVERABLE_ERROR: session_regenerate_id(): Failed to create(read) session ID: memcached " error with these versions: 

```
PHP Version => 7.0.15-0ubuntu0.16.04.4
```

```
php-memcached:
Version => 2.2.0
libmemcached version => 1.0.18
```

**Comment by airinaga** [comment]
Im getting : Failed to create session ID: memcached

with php-fpm 7.12 and memcached 1.4.15

This is in my php-fpm.d/conf* 

php_value[session.save_handler] = memcached
php_value[session.save_path]    = "tcp://serverIP:11211, tcp://serverIP:11211"

**Comment by sodabrew** [comment]
@airinaga What version of php-memcached extension are you using? What version is "php-fpm 7.12" - do you mean "7.1.2" and if so, can you update to the latest PHP 7.1.x?

**Comment by airinaga** [comment]
Sorry, yes php 7.1.2

and php-pecl-memcached-3.0.3-1

Is this fixed in 7.1.7? Being thats the latest current stable release.

**Comment by airinaga** [comment]
Well.. I am able to get it to work when the handler is memcache, but it is slower than molasses.

I get the above error when the handler is memcached. I also set it to memcached in /etc/php.d/40-memcache.ini not sure if that's what I'm supposed to do.

**Comment by sodabrew** [comment]
I don't think it 's a version issue. If you take a look on the thread for the other open issue around sessions, you'll see alternate settings for the timeouts that may work better for you.
