### ISSUE TITLE
Session lock record with PHP 7.0.9

### ISSUE THREAD

**Issue by CassianoCarraro** [php-memcached-dev/php-memcached#269]
I'm using a Memcached session handler normally in PHP 5.6. But with PHP 7 session don't retrieved properly and the follow warning message was triggered in PHP error log: **PHP Warning: session_start(): Unable to clear session lock record.**

Any suggestion?

**Comment by datasage** [comment]
Session settings have changed quite a bit for php 7 version of the extension, you will probably need to tweak your settings a bit to get it to behave as it did in PHP 5.6

**Comment by sodabrew** [comment]
Please state the version of php-memcached that you are using (or the git revision if you're building from source).

**Comment by CassianoCarraro** [comment]
I tried to use repository and build [php7](https://github.com/php-memcached-dev/php-memcached/tree/php7) source branch, but in both case i have the same problem. The versions is as follows:

From repository
Memcached version: 3.0.0-dev
libmemcached version: 1.0.16

From php7 branch:
Memcached version: 3.0.0b1
libmemcached version: 1.0.18

**Comment by beniamin** [comment]
I had same problem and I resolved  the issue by disabling session.lazy_write in php.ini

**Comment by arisro** [comment]
Hey guys,

You can set memcached.sess_lock_expire to your max_execution_time value to avoid that bug from #266. This way the extension won't fall back to the max_execution_time value - which it reads incorrectly.

**Comment by CassianoCarraro** [comment]
I disabled `session.lazy_write` and set `memcached.sess_lock_expire` according my `max_execution_time`, but the problem persists. I found that this problem occurs when many requests is sent in a short time to session_start() with a same session id. This can be simulated with a code that call `session_start()` and then add a `sleep` executing this script many times will throw this error. I think that have a problem to unlock session or another configuration is causing the problem.

**Comment by arisro** [comment]
@CassianoCarraro 

In the case you describe, the error is normal.
Example:
0. See this: https://bugs.php.net/bug.php?id=72345. The maximum execution time is not affected by system calls, stream operations etc. So the time you wait for session_start() doesn't add to the execution time.
1. You have max_execution_time = memcached.sess_lock_expire = 30s
2. You fire a request that keeps the session locked 3s let's say. If you fire 11 requests, they are serialized by the session lock. Your requests will go through 1 by 1.
3. The first request goes in immediately and locks the session for 3s. The seconds request waits 3s then he locks it for another 3s. The thirs requests will wait in total 6 seconds, then lock for 3s.. and so on.
4. The 11th request has to wait 30 seconds. Since session_start() doesn't add to the exection time, you won't get a max execution time error. You will get instead a warning, because of the session locking timeouts (see memcached.sess_lock_retries, memcached.sess_lock_wait_min/max).
Once this timeout happens, your request will go through and be executed - ignoring the lock so to say.

**Comment by beniamin** [comment]
My problem is with parallel requests. If I have an ajax request running and I send another request, both requests are stopped and receive 500 with error from first post.  
I tried to set max_execution_time = memcached.sess_lock_expire, but didn't solve my problem. 
Only disabling session.lazy_write solved my problem.

**Comment by idmssvep** [comment]
I have the same issue, i run a lot of paralell requests and i have repeating "Unable to clear session lock record" fatals. I disabled lazy write and tried following memcached config:

memcached.sess_lock_expire	7200	
memcached.sess_lock_max_wait	not set
memcached.sess_lock_retries	5
memcached.sess_lock_wait	not set
memcached.sess_lock_wait_max	120000
memcached.sess_lock_wait_min	0
memcached.sess_locking	1

with: 
Version	3.0.0-dev
libmemcached version	1.0.16

With older versions on php 5.4 base i have absolutely no issues. It gives me a feeling that on PHP7 they are processed much faster and due to this fact create more blocking requests. One question: Is this issue fixed to PHP 7.0.9, so a up or downgrade could help?

**Comment by arielkung** [comment]
Confirming here in php 7.0.12 if you set a fixed value for memcached.sess_lock_expire the issue goes away.
Message "PHP Warning: session_start(): Unable to clear session lock record." will appear anyway if your session is locked more than the time you set of course.

**Comment by bzabos** [comment]
Please read up on how these values are consumed: https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini

Increasing `sess_lock_wait_max` is only increasing the maximum seconds to which php will perform its exponential back off routine for retries. Increasing this value does nothing when `sess_lock_wait_min` is left untouched. If we want php to continue retrying at an acceptable interval, I don't believe these are the keys we should be adjusting. Disabling `lazy_write` also seems like a bad idea.

Can anyone see why the solution wouldn't be to simply increase `sess_lock_retries` to a number that would result in an acceptable wait time for your specific scenario?

Eg. Where default `sess_lock_wait_min=1000` and default `sess_lock_wait_max=2000` and increased `sess_lock_retries=10`, our retry wait will accumulate as `1s+2s+... Ns`, giving us a total wait of 19 seconds of waiting and retrying for session lock to be released by other requests; logically, it makes sense to formulate rough equality with your `max_execution_time`.

**Comment by bzabos** [comment]
Please read up on how these values are consumed: https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini

Increasing `sess_lock_wait_max` is only increasing the maximum seconds to which php will perform its exponential back off routine for retries. Increasing this value does nothing when `sess_lock_wait_min` is left untouched. If we want php to continue retrying at an acceptable interval, I don't believe these are the keys we should be adjusting. Lowering `sess_lock_expire` is just highjacking the session from other, long running, requests — is that the desired behaviour? Disabling `lazy_write` also seems like a bad idea.

Can anyone see why the solution wouldn't be to simply increase `sess_lock_retries` to a number that would result in an acceptable wait time for your specific scenario?

Eg. Where default `sess_lock_wait_min=1000` and default `sess_lock_wait_max=2000` and increased `sess_lock_retries=10`, our retry wait will accumulate as `1s+2s+2s+... Ns`, giving us a total wait of 19 seconds of waiting and retrying for session lock to be released by other requests; logically, it makes sense to formulate rough equality with your `max_execution_time`.

**Comment by woolardfa** [comment]
For our Moodle site, we use memcached for PHP sessions. Because of the way Moodle uses the session handler in its AJAX calls (several issued before main page request finishes) we often get blocked session_start() calls. See [this bug](https://tracker.moodle.org/browse/MDL-53713) and [this bug](https://tracker.moodle.org/browse/MDL-57477) for details.

To get the new version to behave like the old one, we set the lock_wait_min and _max to the same reduced value of 150. This makes the spin lock retry 150 msec, as was the default in 2.2.x. Moodle config default is to wait a max of 120 secs to attain a session lock, so we set the retry count to 800 (120 / .15).

One or two seconds seems to be much to long to wait between attempts; much better to make several frequent attempts waiting (sleeping) only 150 msec at a time.

**Comment by sodabrew** [comment]
Ive read through this ticket and I'm not sure what problem or change request is still outstanding.

**Comment by andrerom** [comment]
Well somwhow it seems session locking might be broken with php7, similar issue here.

**Comment by sodabrew** [comment]
@andrerom As I wrote, I don't fully understand the specific problem(s?) that people are having in this thread. If the problem(s?) is also affecting you, can you help to explain what would resolve it?

**Comment by woolardfa** [comment]
I believe the session locking problem isn't so much an issue with the php_memcached as it is with PHP (all versions). See https://bugs.php.net/bug.php?id=71962.

**Comment by sodabrew** [comment]
I still don't understand if there is something that needs to be fixed or changed or better documented.

@woolardfa The bug you linked is specific to the memcached extension, it just happens to be filed in the PHP bug tracker, and I don't see in what way the PHP version affects the bug.

**Comment by woolardfa** [comment]
@sodabrew, you are correct. As I said in previous message, the issue is not in php_memcached.

**Comment by idmssvep** [comment]
With the explanation from [woolardfa](https://github.com/php-memcached-dev/php-memcached/issues/269#issuecomment-271123804) i could successfully resolve the issue from my application. Thanks!

**Comment by idmssvep** [comment]
Can the ini file description be updated please:

https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini

Section:
; The time, in seconds, before a lock should release itself.
; Setting to 0 results in the default behaviour, which is to
; use the memcached.sess_lock_max_wait setting. If that is
; also 0, max_execution_time will be used.
memcached.sess_lock_expire = 0;

"memcached.sess_lock_max_wait" is deprecated, i assume that "memcached.sess_lock_wait_max" will be i place but i´d like to know.

**Comment by mikealmond** [comment]
Any update on this?

**Comment by nitinsbuzz** [comment]
Any chance queing requests on the server side can solve this problem?

**Comment by nitinsbuzz** [comment]
If this is an issue regarding only ajax requests, how about `session_write_close()` a.s.ap. after the ajax call? Any experience with this option? Will it remove the lock? 

http://php.net/manual/en/function.session-write-close.php 
http://php.net/manual/en/function.session-write-close.php#63970

**Comment by woolardfa** [comment]
session_write_close will end up clobbering the session data. session_abort() is the way to leave it alone.

**Comment by nitinsbuzz** [comment]
@woolardfa would session_abort() has also work immediatly after session_write_close() in case session data needs update on ajax call?

**Comment by woolardfa** [comment]
No. Use one or the other. The point is that you have to detect whether or not PHP/session/memcached was truly successful in establishing the lock entry (semaphore), and thus acquiring the right to update the session content, OR whether it just gave up after trying the specified number of times (timed out), and returned a True (the bug in session_start()) anyway. In this latter case, the session content given to the usurping process will be empty... and when session_write_close is called, or the page is allowed to end normally, that bogus (empty) session data will be written back clobbering the valid data. Calling session_abort will prevent that.

**Comment by nitinsbuzz** [comment]
@woolardfa Thank you for the clear explanation!

**Comment by nitinsbuzz** [comment]
I think the problem is with async requests (using a service worker). Only if memcached can handle async requests would it solve the problem or move long processes to the background to make sure sync requests do not get blocked.

**Comment by tvlooy** [comment]
For people that don't completely understand what this locking is, I recommend this article: https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/

**Comment by nitinsbuzz** [comment]
How about moving the session files to memory for faster and multi access or creating virtual readonly files so that reading does not lock the file? Is this possible for memcached?

**Comment by jaccoTopVintage** [comment]
@sodabrew , while I'm not entirely sure about the cause of the issue, the issue is quite serious: it effectively disqualifies the use of memcached as a session save handler for PHP >= v7.0.

Our logfiles are rapidly accumulating these errors, even for just staging (=internal testing) traffic.

```txt[Tue Jun 13 09:57:08.391456 2017] [:error] [pid 1279] [client 172.31.4.11:30828] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 09:59:34.545330 2017] [:error] [pid 863] [client 172.31.47.37:62727] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:02:35.437714 2017] [:error] [pid 1420] [client 172.31.17.123:2875] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:07:36.574186 2017] [:error] [pid 770] [client 172.31.4.11:13979] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:08:12.651084 2017] [:error] [pid 23486] [client 172.31.47.37:33523] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:11:28.548426 2017] [:error] [pid 1573] [client 172.31.4.11:33060] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:11:37.436829 2017] [:error] [pid 23723] [client 172.31.4.11:3833] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:14:17.058926 2017] [:error] [pid 23717] [client 172.31.4.11:4263] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:15:10.176169 2017] [:error] [pid 1104] [client 172.31.47.37:19174] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:16:32.894139 2017] [:error] [pid 23813] [client 172.31.17.123:58336] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:17:15.524989 2017] [:error] [pid 1111] [client 172.31.4.11:15525] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:22:59.417394 2017] [:error] [pid 1906] [client 172.31.17.123:6021] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:22:59.432654 2017] [:error] [pid 1816] [client 172.31.47.37:2256] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:23:08.161788 2017] [:error] [pid 1787] [client 172.31.17.123:6025] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:23:16.484796 2017] [:error] [pid 24015] [client 172.31.17.123:59396] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:23:24.383012 2017] [:error] [pid 2140] [client 172.31.47.37:2320] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:23:43.852884 2017] [:error] [pid 1816] [client 172.31.47.37:2338] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:24:25.161398 2017] [:error] [pid 24203] [client 172.31.47.37:35983] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:03.566216 2017] [:error] [pid 1458] [client 172.31.17.123:24316] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:27.959560 2017] [:error] [pid 1496] [client 172.31.17.123:24374] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:28.079258 2017] [:error] [pid 24287] [client 172.31.17.123:60018] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:28.271585 2017] [:error] [pid 24290] [client 172.31.17.123:60046] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:28.613682 2017] [:error] [pid 2199] [client 172.31.17.123:6733] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:28.663198 2017] [:error] [pid 1343] [client 172.31.17.123:24390] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:28.970449 2017] [:error] [pid 1496] [client 172.31.17.123:24374] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:29.490061 2017] [:error] [pid 24290] [client 172.31.17.123:60046] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:27:29.857074 2017] [:error] [pid 2199] [client 172.31.17.123:6733] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:28:46.994038 2017] [:error] [pid 2335] [client 172.31.47.37:3174] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:29:00.161461 2017] [:error] [pid 2335] [client 172.31.47.37:3174] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:29:20.098777 2017] [:error] [pid 1787] [client 172.31.4.11:35818] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:32:59.001278 2017] [:error] [pid 2195] [client 172.31.17.123:7623] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:33:45.308154 2017] [:error] [pid 24287] [client 172.31.4.11:7269] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:38:55.447610 2017] [:error] [pid 1823] [client 172.31.47.37:22896] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:39:56.155497 2017] [:error] [pid 24238] [client 172.31.4.11:8209] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:40:07.865303 2017] [:error] [pid 1967] [client 172.31.4.11:19039] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:40:12.868631 2017] [:error] [pid 2609] [client 172.31.17.123:8763] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:40:19.048030 2017] [:error] [pid 1855] [client 172.31.17.123:26476] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:40:25.111417 2017] [:error] [pid 1998] [client 172.31.17.123:26432] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:42:25.782704 2017] [:error] [pid 24824] [client 172.31.17.123:62482] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:42:30.814022 2017] [:error] [pid 2092] [client 172.31.17.123:26826] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:43:04.932733 2017] [:error] [pid 1998] [client 172.31.4.11:19519] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:43:45.679325 2017] [:error] [pid 2795] [client 172.31.4.11:38020] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:44:45.618017 2017] [:error] [pid 24853] [client 172.31.4.11:8963] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:44:46.826418 2017] [:error] [pid 2865] [client 172.31.4.11:38170] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:45:20.161990 2017] [:error] [pid 2095] [client 172.31.17.123:27296] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:45:41.488957 2017] [:error] [pid 2795] [client 172.31.17.123:9643] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:47:00.471857 2017] [:error] [pid 3022] [client 172.31.4.11:38542] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:50:18.691312 2017] [:error] [pid 2957] [client 172.31.4.11:39036] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:50:18.752100 2017] [:error] [pid 2323] [client 172.31.4.11:20717] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:50:20.614374 2017] [:error] [pid 3008] [client 172.31.17.123:10439] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:51:26.870465 2017] [:error] [pid 2437] [client 172.31.17.123:28202] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:51:50.680096 2017] [:error] [pid 3135] [client 172.31.17.123:10619] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:52:51.911556 2017] [:error] [pid 3053] [client 172.31.4.11:39432] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:52:53.204019 2017] [:error] [pid 2415] [client 172.31.4.11:21093] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:53:17.773753 2017] [:error] [pid 2465] [client 172.31.47.37:25128] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:53:51.918845 2017] [:error] [pid 25093] [client 172.31.17.123:64284] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:54:47.174806 2017] [:error] [pid 25181] [client 172.31.17.123:64438] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:56:19.245320 2017] [:error] [pid 3020] [client 172.31.4.11:40018] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:57:38.188590 2017] [:error] [pid 2704] [client 172.31.17.123:29226] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 10:58:47.985600 2017] [:error] [pid 25400] [client 172.31.47.37:41417] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:02:28.356013 2017] [:error] [pid 25398] [client 172.31.4.11:11795] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:03:42.262363 2017] [:error] [pid 25596] [client 172.31.4.11:11971] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:09:05.051044 2017] [:error] [pid 25729] [client 172.31.17.123:2581] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:09:05.305337 2017] [:error] [pid 25667] [client 172.31.17.123:2575] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:09:52.250367 2017] [:error] [pid 25729] [client 172.31.4.11:12935] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:12:07.299454 2017] [:error] [pid 3157] [client 172.31.17.123:31354] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:12:59.271920 2017] [:error] [pid 3666] [client 172.31.47.37:9914] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:13:26.276822 2017] [:error] [pid 25868] [client 172.31.47.37:43489] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:13:46.663606 2017] [:error] [pid 25922] [client 172.31.17.123:3295] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:13:54.835686 2017] [:error] [pid 3742] [client 172.31.47.37:10016] PHP Warning: session_start(): Unable to clear session lock record in (...)
[Tue Jun 13 11:15:42.915935 2017] [:error] [pid 2904] [client 172.31.4.11:24571] PHP Warning: session_start(): Unable to clear session lock record in (...)
```

I'm not sure exactly *what* causes the issue, but we confirmed that it is caused by PHP7: an otherwise identical PHP 5.6.30 setup does not have the issue.

I would be happy to assist in finding the cause of the issue, if that would help speed up a fixing it.

**Comment by tvlooy** [comment]
@jaccoTopVintage try this:
ini_set('memcached.sess_lock_wait_min', 150);
ini_set('memcached.sess_lock_wait_max', 150);
ini_set('memcached.sess_lock_retries', ini_get('max_execution_time') * 1000 / 150);
remove all your other ini_sets (including session.lazy_write)

This is the fix that I suggested here https://github.com/php-memcached-dev/php-memcached/pull/350 and we are running a high traffic site in production with these settings without any issues so far. /cc @sodabrew

**Comment by jaccoTopVintage** [comment]
@tvlooy thanks for the comment!

I take it  
`  ini_set('memcached.sess_lock_expire', ini_get('max_execution_time'));`  
can/should also stay, because it seems to work in union with:
`  ini_set('memcached.sess_lock_retries', ini_get('max_execution_time') * 1000 / 150);`  
?

**Comment by sodabrew** [comment]
To everyone who commented on this issue: Please look at PR #350 and test out those values. If they work for most people, then I will accept them as the new defaults in the next version of this extension.

**Comment by woolardfa** [comment]
We've been using 150/150 and 800 ... this mimics the spin lock behavior of the previous strategy, and the overall timeout (give up time) is 120 secs... which is what Moodle (the app we're running) defaulted to in its configs.

**Comment by tvlooy** [comment]
@jaccoTopVintage can you confirm the new values work for you? ```sess_lock_expire``` is not used by the 7.x extension and thus has no effect

**Comment by jaccoTopVintage** [comment]
@tvlooy I will confirm tomorrow, when I can monitor the results during the day.

**Comment by jaccoTopVintage** [comment]
If `sess_lock_expire` is not used the php 7.x extension, then why is it still [listed in the memcached.ini file](https://github.com/php-memcached-dev/php-memcached/blob/php7/memcached.ini#L31)?
```ini
; The time, in seconds, before a lock should release itself.
; Setting to 0 results in the default behaviour, which is to
; use the memcached.sess_lock_max_wait setting. If that is
; also 0, max_execution_time will be used.
memcached.sess_lock_expire = 0;
```
I'm not contradicting you, just curious if the `.ini` file is up to date or not?

**Comment by tvlooy** [comment]
@jaccoTopVintage my bad. You are right it is in use. I grepped the code and couldn't find it and saw that it was removed in dc5b22a8dace7373c1ef9d2946e89a660ed35b20#diff-f76062ebbcf30f0491af9ca937d17762 but I didn't see that it got replaced with the MEMC_SESSION_INI_ENTRY macro so I had to grep for lock_expire. But: the default value is 0 and then it automatically defaults to the max_execution_time. So no need to change it I think

**Comment by tvlooy** [comment]
Yes but "the server has failed" comes from libmemcached. I think at that point you are killing the server where you are running your memcached on and the problem lies there, not in the php-memcached extension.

**Comment by jaccoTopVintage** [comment]
Well, the proposed default settings are, without question, a huge improvement to the current default settings. So, I support the idea of merging Please look at PR https://github.com/php-memcached-dev/php-memcached/pull/350.

I fear however, that there is (also) a deeper underlying problem, because we never had any noteworthy issues with memcached backed session with out PHP 5 servers.

**Comment by jaccoTopVintage** [comment]
@tvlooy , What are the Memcached settings you use, for your high traffic production site?

More specifically, what is are numbers your production environment uses for the limit of simultaneous incoming connections (`-c` flag) and the memory cap (`-m` flag)?

**Comment by tvlooy** [comment]
@jaccoTopVintage -c 8192, -m 128. That is for sessions only (so was the ~140 cmd/s). We run a separate instance for user cache with -c 8192, -m 1536 that is doing ~718000 cmd/s.

**Comment by tvlooy** [comment]
@CassianoCarraro what was your status with this issue? Can you verifiy the solution above?

**Comment by jaccoTopVintage** [comment]
We finally fixed the issues we had with the memcached backed PHP sessions. The 'solution' for us was to set:
```php
ini_set('session.lazy-write', 0); // Mimic PHP5 behaviour
```
This is, of course, not a solution, but rather a workaround. I'm guessing that the lazy-write option somehow walks a code path that triggers errors, or at least, incompatibilities with the memcached server. My C skill are way too rusty to find the issue myself, but I'm hoping this information can at least help someone else find out the root cause of the issue.

**Comment by CassianoCarraro** [comment]
@tvlooy I updated my PHP and memcached lib. Now I'm working with:
PHP: 7.0.20
Memcached version: 3.0.3
libmemcached version: 1.0.18

I did some tests in my environment with default config's and all is working fine now. In addition, I performed some tests delaying the requests to simulate the problem. In this case I did some adjustments in configuration vars `memcached.sess_lock_expire `and `memcached.sess_lock_wait_max` as the @idmssvep indicated and work fine too.

**Comment by tvlooy** [comment]
Thanks! Anyone else that is following this report? Please test and report your findings.

**Comment by nadalizadeh** [comment]
My warnings disappeared with the following configuration as @tvlooy suggested.

```
; Wait for 150 ms initially
memcached.sess_lock_wait_min = 150
; Wait for 500 ms in the next retries
memcached.sess_lock_wait_max = 500
; Retry for 60 times overally (max time would be 60 x 500 ms)
memcached.sess_lock_retries = 60
; Total time that a lock exists is 40 seconds which is equal to my max_execution_time
memcached.sess_lock_expire = 40
```
-> Upgrading to the latest php-memcached from git repository didn't help without the configuration above.

**Comment by baurmatt** [comment]
Still happening to us even thought we have set the recommended memcached config options :(

**Comment by tvlooy** [comment]
we are stull running fine in production without issues

**Comment by terryzwt** [comment]
I fixed the problem using below config. php:5.6.18
```bash
[session]
session.lazy_write = 0

[memcached]
memcached.sess_locking = On
memcached.sess_lock_wait = 150000
memcached.sess_lock_max_wait = 30;
memcached.sess_lock_expire = 0;
memcached.sess_consistent_hash = Off
memcached.sess_remove_failed = 1
memcached.sess_number_of_replicas = 0
memcached.sess_binary = Off
memcached.sess_randomize_replica_read = Off
memcached.sess_connect_timeout = 1000
memcached.sess_sasl_username = NULL
memcached.sess_sasl_password = NULL
memcached.compression_type = "fastlz"
memcached.compression_factor = "1.3"
memcached.compression_threshold = 2000
memcached.serializer = "igbinary"
memcached.use_sasl = Off
memcached.store_retry_count = 2
```

**Comment by lichunqiang** [comment]
@tvlooy can you share your full configuretions?

After try the current master branch, and below settings, it does not work for me.

@sodabrew I tried the lastest commit, but not works.

Is any update for this @all ?

**Comment by tvlooy** [comment]
```
$ php -v
PHP 7.1.8 (cli) (built: Aug  7 2017 13:46:59) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies
$ php -i | grep ^memcached
memcached
memcached support => enabled
memcached.compression_factor => 1.3 => 1.3
memcached.compression_threshold => 2000 => 2000
memcached.compression_type => fastlz => fastlz
memcached.default_binary_protocol => no value => no value
memcached.default_connect_timeout => 0 => 0
memcached.default_consistent_hash => no value => no value
memcached.serializer => igbinary => igbinary
memcached.sess_binary_protocol => no value => no value
memcached.sess_connect_timeout => 1000 => 1000
memcached.sess_consistent_hash => 1 => 1
memcached.sess_lock_expire => 0 => 0
memcached.sess_lock_max_wait => not set => not set
memcached.sess_lock_retries => 2000 => 2000
memcached.sess_lock_wait => not set => not set
memcached.sess_lock_wait_max => 150 => 150
memcached.sess_lock_wait_min => 150 => 150
memcached.sess_locking => 1 => 1
memcached.sess_number_of_replicas => 0 => 0
memcached.sess_persistent => no value => no value
memcached.sess_prefix => memc.sess.key. => memc.sess.key.
memcached.sess_randomize_replica_read => no value => no value
memcached.sess_remove_failed_servers => no value => no value
memcached.sess_sasl_password => no value => no value
memcached.sess_sasl_username => no value => no value
memcached.sess_server_failure_limit => 0 => 0
memcached.store_retry_count => 2 => 2
```

**Comment by terryzwt** [comment]
Finally I fixed the problem in symfony.
reference to this: https://labs.madisoft.it/scaling-symfony-sessions-with-memcached/

The main idea is add a wrapper to addServer to void multiple memcache session create.

**Comment by lichunqiang** [comment]
hi @tvlooy  can you take out the memcached version and libmemcached version?

@terryzwt I just using single server now,

I haid tried memcached version `3.0.0` and `3.0.3` and the  master branch, all failed. I have no idea what issued the problem..

**Comment by tvlooy** [comment]
php-memcached = 3.0.3
libmemcached = 1.0.16
memcached = 1.4.15

**Comment by terryzwt** [comment]
@lichunqiang you can try 
```bash
telnet your-memcache-server-ip 11211
```
then type "stats", check the "curr_connections" session to get how many connection to memcache server.
Then you will be realize the problem.

**Comment by lichunqiang** [comment]
@terryzwt 你的意思是连接数导致的问题？但是我现在是单机进行测试的。英语不好，还是中文方便。。

**Comment by tvlooy** [comment]
thanks Google for Google translate ;-)
the number of connections can be a problem but I don't see how terryzwt got to that conclusion ...

@terryzwt about your blog article. Unlike Memcached, Redis does not have session locking support. I just wanted to point that out to you maybe you can elaborate on that in your next blog article. I would be interested in your findings

**Comment by terryzwt** [comment]
@lichunqiang 我在实际场景中,memcache连接数超过4000,就很容易出现lock问题.后来在代码层面进行连接复用,大概控制在200左右,基本lock问题就不会出现了.链接复用的方式就是上面告诉你的博客链接里的方法.在addServer外面封装一层.

@tvlooy it's not my blog :) My blog is www.dplor.com, most of the articles are Chinese.

**Comment by lichunqiang** [comment]
@tvlooy Hi, This can resolved the problem, but casued a new issue, the  `session_start` in php slow log.

It is casued by time of the settings?

**Comment by fishfacemcgee** [comment]
@tvlooy With the settings you have, have you seen any issues with sessions started for a request that eventually hits a fatal error staying locked until the lock expiration time (which would be the max execution time)? I'm using similar settings on a staging environment and the locking issue is effectively resolved except in this edge case. I don't want to assume that fatal errors are impossible in my app so I'm trying to figure out if there's anything I can do besides setting the lock expiration time to something lower.

**Comment by adv4000** [comment]
For me with PHP7.1
Changed in `/etc/php-7.1.d/50-memcached.ini`
memcached.sess_locking = On
to
memcached.sess_locking = Off

Looks like fixed this error.

**Comment by Hotte512** [comment]
Yeah... but no more session locking :(

Hope it'll be fixed someday...

**Comment by tvlooy** [comment]
@lichunqiang if that is slow, that means your memcache is slow. It could be that the server where memcache runs is under load
@fishfacemcgee no I didn't. What kind of setup are you running?
@adv4000 yeah. It's pretty normal that problems with a feature (session locking) go away when you turn off that feature

**Comment by SvenRtbg** [comment]
Reading through the comments, I see several similarities to what I experienced.

The question was asked if the new default settings in #350 work better. Yes, they do. Waiting at least 1000ms (as the old default for sess_lock_wait_min) is ridiculous: PHP scripts usually are executed within 100ms if they do basic stuff - why would anyone be willing to wait an entire second? My experience is that you should fine-tune the minimum value to something that is slightly larger than the minimum execution time of a script on your server. I have chosen 100ms.

The maximum waiting time or the reason for exponential backoff has no good explanation, but I'm fine with it existing, I suppose that you would be able somehow to overload a Memcached server with lock checks. However, the current default of 2000ms is also too big for my liking, I chose 400ms.

The thing that is not documented very good is how these two values interact with the sess_lock_retries and the sess_lock_expire values. My understanding is that the sess_lock_expire value should be greater than max_execution_time, and that the retries should also be a reasonably high number.

Why should sess_lock_expire be greater than max_execution_time? Because max_execution_time does not count every time PHP is using - but sess_lock_expire does. If PHP waits for a remote system to answer, like databases, that time is not counted when evaluating the max_execution_time, so you can end up executing scripts for longer than the max_execution_time suggests. The lock however is based on wall time. My suggestion would be to set the sess_lock_expire value to at least 1.5 times the value of max_execution_time, just to ensure that an aborted script still is within the time the lock exists.

Regarding sess_lock_retries, this value should also be high enough to cover for edge cases. Assume that you have three long running requests coming in at the same time - each run for 55 seconds. The lock expiry time is set to 100 seconds. Min/max wait time is set to 100ms.

If you want to retry for the whole lifetime of a lock, you'd have to set sess_lock_retries to 100s/100ms = 1000.
However, the first request locks the session for 55 seconds, then releases the lock. The second request aquires the lock after around 55.1 seconds, creating a new lock that would last for another 100 seconds. It will release that lock after 110 seconds (55s * 2 requests). However, the third request has given up after it retried for 100 seconds, or 1000 times. It will corrupt the session because it overrides the existing lock, reads the session in its currently stored state (which is after the first script ran), and will write back it's new state, overwriting any changes that the second script had made.

I understand that having "long running web request scripts" is not ideal, but that's what I have to deal with - and the documentation should give some hints regarding the configuration considerations for these values.

So TL;DR:
* __sess_lock_wait_min__ = aim for a resonably low value that is slightly greater than your average "fast" script execution time.
* __sess_lock_wait_max__ = aim for a value that looks like your Memcached server can handle it if you experience some heavy load situations.
* __sess_lock_expire__ = aim for a high enough value that should at least be max_execution_time, but possibly multiple times that time. Consider if you'd be likely to experience long running scripts and concurrent calls for the same session id. As an upper boundary for this value, consider that a single session will be unresponsive for at least this long if things go really bad.
* __sess_lock_retries__ = higher is better. There is nothing wrong with retrying for longer than the lock expiry time is configured. Remember that if you stop retrying, you'll possibly corrupt the existing session because the script will start using the session in it's existing state despite it being locked.

**Comment by onassar** [comment]
Did anyone come to a conclusive, consistent answer on this one? I'm running:
php-dev: `1:7.2+60ubuntu1` (resulting in `7.2.5-0ubuntu0.18.04.1`)
libmemcached: `1.0.18-4.2`
php-memcached: `3.0.1+2.2.0-1build2`

My sessions are running through AWS ElastiCache

After reading this thread and [this post](https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/), I'm at a loss as to what the best way to:
1) Reproduce this issue consistently
2) Resolve the issue

**Comment by fishfacemcgee** [comment]
@onassar I don't think there is a way to "solve" the issue from the config side of things besides not using locked sessions. At least I wasn't able to; I could just minimize the frequency and severity of the locking by using the values proposed as new defaults in #350. The problem (based off the ma.ttias.be post you linked) is that Request B has to wait for Request A's session to end. Depending on how your application interacts with Sessions, this may require the request to end, which, depending on the speed of your requests, may be a while.

In my case, every request _always_ started a session, and never closed it until the request ended. What we've been doing to address the issue is change both behaviors:

- Only start session on requests that actually need to use `$_SESSION`
- Close the session (at least the request's ability to write to the session) as soon as you're done using it, especially if it's early in the request.

If you know for certain that your application does not rely on the session data in a way that mandates locking, you could just disable session locking and call it day.

**Comment by onassar** [comment]
Thanks for the writeup @fishfacemcgee 
At the moment, I've simply set `session.lazy_write` to `false` and am going to monitor our server to see what happens. The reason I presumed a possible "solution" was because I _just_ upgraded from PHP `5.6.x` when I started noticing this. So my presumption was that something in the newer libraries (PHP, libmemcached, php-memcached, Ubuntu 18.04, newer apache, etc etc) isn't playing well together.

Or is that the default session and memcached configuration options in my PHP `5.6.x` install were simply so "loose" that they didn't cause the issue to show it's head?

Ideally, I'd like to say that I know exactly when the writing is happening; but that would require a fair amount of refactoring to ensure that's the case, which could then introduce application/middle-wear bugs. So a rock and a hard place.

A few posts in this thread list `session.lazy_write` being set to `false` as not the "correct" way. Tbh, I don't understand what that setting does. PHP's docs on that are somewhat vague:
> session.lazy_write, when set to 1, means that session data is only rewritten if it changes. Defaults to 1, enabled.

If you could enlighten me as to why setting this to `false` would fix the locking issue, I'd be all ears.
:)

**Comment by woolardfa** [comment]
Just an FYI... have tested PHP 7.2 (7.2.6), the underlying issue where session_start returns true when it in fact failed to acquire the session lock, and subsequently corrupts the existing session data, has been fixed.

A call to session_start() now returns false when it failed to acquire the session lock.

**Comment by onassar** [comment]
Hmmm I'm running `7.2.7` and still running into the issue..

**Comment by Eimantas123** [comment]
php 7.2.15, libmemcached version 1.0.18
problems still occur.

**Comment by csev** [comment]
Just an update - I am using AWS Elasticache as my Memcache and PHP 7.1.  Setting `session.lazy_write = Off` got rid of the message.  I am 100% guessing here, but this behavior suggests that with lazy_write on, it holds the lock a little while longer - even though it *knows* the request is done and that the session is unmodified.  When it writes it back the lock is released.  Good thing my memcache is pretty fast / underutilized for now :)

**Comment by csev** [comment]
Update.  I was able to watch error logs and tweak all these values live and figure out what worked and what did not.  Turning off `session.lazy_write` only reduced the frequency of the errors.  Also trying to set the `_min` and `_max` to 150 as described above does not stop the errors.  The only thing that stopped the errors are to turn `ini_set('memcached.sess_locking', '0');` - and then turn `lazy_write` back on.  I read that Redis does not lock at all. So this feels like the simplest / best path.  (This is PHP 7.1 and libmemcached 1.0.18 ).  Hope this helps.

**Comment by woolardfa** [comment]
@csev Good news that you've determined your simplest/best path, and do not want to discourage you, but do want to offer some things to consider if you choose to keep using memcached for sessions.

Firstly, I'd recommend getting to a current version of PHP where the fundamental bug is fixed. The bug is not in libmemcached, or in php-memcached; it's in PHP.

The issue is not so much how php_memcached is configured (i.e. _min, _max), because like you said, changing how those are configured didn't eliminate the errors--and they weren't meant to, they were just meant to a) mimic the old session acquisition timings, and b) try to reduce the frequency of the errors based on how one particular application, Moodle, was designed.

The issue is more about how sessions are handled at the application level, and whether your application code uses PHP's session management on almost every browser request, like Moodle currently does, (page requests, and subsequent AJAX requests), or if it's more selective. Also, does the application code detect whether the $_SESSION super global is valid or not (most all the time we take that for granted, and that's the patch I added to Moodle's memcached session startup, until PHP was fixed).

So, you're right, going with no session locks will eliminate the errors, because that particular lock/semaphore entry won't be created to begin with, and no attempt will be made to remove it. If you're application will work with no concurrency checks (last to touch it wins), then yeah, that's the ticket.

**Comment by csev** [comment]
@woolardfa - Thanks a ton - My application is Tsugi - an EdTech app like Moodle.  It can survive with "eventual consistency" and "last write wins".  I am encouraged by your suggestion to move beyond 7.1 - what version of PHP is this fixed in?   I am a little gun shy as, the road through and to 7.0 and 7.1 was kind of rocky, stuff was not getting fixed, and even the apt repos were wonky and non-standard.  So when I got something working I just breathed a sigh of relief and froze my infrastructure.  But that was a year ago and I am sure things are better so I am heartened to give it another go if I know what version to go to - I am nervous about jumping to the absolute latest.  Again, thanks.

**Comment by SvenRtbg** [comment]
Nobody has been doing this in this issue, but I think in order to get the full picture of a problem report you should add at least all the settings I mentioned in my comment above: https://github.com/php-memcached-dev/php-memcached/issues/269#issuecomment-366285778

sess_lock_wait_min, sess_lock_wait_max, sess_lock_expire, sess_lock_retries. Note that the _min and _max times are basically irrelevant for the functioning of the session in general, they are being used to fine-tune timing behavior. The most important settings are lock_expire (also compared to your max_execution_time) and lock_retries. With these set the wrong way, you may end up overwriting your session unintentionally.

**Comment by woolardfa** [comment]
@csev The pain points in Moodle (all handled by moodlehq) were mostly in the 5.x -> 7.x migration. I imagine there ought to be very few going from 7.1 -> 7.3. We've tried to keep our sites fairly up-to-date, and didn't see any issues when we moved from 7.1.x. to 7.2.x.

I believe the bug was fixed in 7.2.6 onward, so the current stable of either 7.2 or 7.3 will be prudent... but then, like I said earlier, it will just mean that your application code can then correctly detect whether the session (lock) was acquired or not before it proceeds.

**Comment by csev** [comment]
@woolardfa I upgraded to 7.3 and everything is working fine and I am using the default settings and seeing no lock issues.  Thanks for your advice.

**Comment by murraycollingwood** [comment]
I'm using php 7.3 and it's still a problem.
I've gone with the config changes to see how this impacts the incidence.
If it remains a problem then I'm seriously considering turning locking off.

**Comment by murraycollingwood** [comment]
I'm using php 7.3 and it's still a problem.
The config changes _wait _min _max made no difference, in fact I think it got worse.
I have now turned off locking and it seems to have solved the locking problem.
I also enabled lazy_write, although I'm not sure if that was necessary.

However, as discussed above, turning off locking is dependent upon how you use your session data.  I think most of my usage should be fine, I guess the next few days will be telling.

**Comment by dytyniuk** [comment]
Hello everyone.

I have read carefully all the comments and solutions proposed: starting with `memcached.sess_lock_*` settings changed and up to sessions locks turned off.

Frankly, I'm strongly convinced, the issue is not PHP-related, while specific to this extension. Details are the following:
* an application is running in Docker image based on `php/7.3.16-fpm-alpine` with both `memcache` and `memcached` extensions installed (we need both, since this is our internal "base" image for all PHP apps)
* All off `memcached.*` and `memcache.*` settings are left default:
```
memcache support => enabled
memcache.allow_failover => 1 => 1
memcache.chunk_size => 32768 => 32768
memcache.compress_threshold => 20000 => 20000
memcache.default_port => 11211 => 11211
memcache.hash_function => crc32 => crc32
memcache.hash_strategy => consistent => consistent
memcache.lock_timeout => 15 => 15
memcache.max_failover_attempts => 20 => 20
memcache.prefix_host_key => 0 => 0
memcache.prefix_host_key_remove_subdomain => 0 => 0
memcache.prefix_host_key_remove_www => 1 => 1
memcache.prefix_static_key => no value => no value
memcache.protocol => ascii => ascii
memcache.redundancy => 1 => 1
memcache.session_prefix_host_key => 0 => 0
memcache.session_prefix_host_key_remove_subdomain => 0 => 0
memcache.session_prefix_host_key_remove_www => 1 => 1
memcache.session_prefix_static_key => no value => no value
memcache.session_redundancy => 2 => 2
memcache.session_save_path => no value => no value


memcached support => enabled
libmemcached version => 1.0.18
memcached.compression_factor => 1.3 => 1.3
memcached.compression_threshold => 2000 => 2000
memcached.compression_type => fastlz => fastlz
memcached.default_binary_protocol => Off => Off
memcached.default_connect_timeout => 0 => 0
memcached.default_consistent_hash => Off => Off
memcached.serializer => php => php
memcached.sess_binary_protocol => On => On
memcached.sess_connect_timeout => 0 => 0
memcached.sess_consistent_hash => On => On
memcached.sess_consistent_hash_type => ketama => ketama
memcached.sess_lock_expire => 0 => 0
memcached.sess_lock_max_wait => not set => not set
memcached.sess_lock_retries => 5 => 5
memcached.sess_lock_wait => not set => not set
memcached.sess_lock_wait_max => 150 => 150
memcached.sess_lock_wait_min => 150 => 150
memcached.sess_locking => On => On
memcached.sess_number_of_replicas => 0 => 0
memcached.sess_persistent => Off => Off
memcached.sess_prefix => memc.sess.key. => memc.sess.key.
memcached.sess_randomize_replica_read => Off => Off
memcached.sess_remove_failed_servers => Off => Off
memcached.sess_sasl_password => no value => no value
memcached.sess_sasl_username => no value => no value
memcached.sess_server_failure_limit => 0 => 0
memcached.store_retry_count => 2 => 2
```

* as soon as you set `session.save_handler=memcached` and put any memcached hostname to `session.save_path`, consecutive XHR calls to the backed start to fail with `session_lock` error
* but, as soon as you change your `session.save_handler` to "legacy" `memcache` (`session.save_handler=memcached`) and modily `session.save_path` a bit:
```
session.save_handler=memcache
session.save_path=tcp://<hostname>:<port>/ # <port> is still required even if you use default 11211
```
Everything works as it should.

So, either default settings for `memcached` are missing proper tuning compared to `memcache` ones. Or there's something wrong with sessions locking on `memcached` side. Again, I do think so, since "legacy" `memcache` works like a charm 🤷‍♂️

**Comment by xobotyi** [comment]
just some comment.

**Comment by michnovka** [comment]
I still dont think this is resolved. I had to fall back to using files for sessions

**Comment by Misosooup** [comment]
Same here, still getting this issue with 7.4.33
